spring.application.name=msvc-users
server.port=8001

# PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/finflow_users}
spring.datasource.username=${DB_USERNAME:finflow}
spring.datasource.password=${DB_PASSWORD:finflow123}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=finflow-secret-key-2024-very-long-string-for-security
jwt.expiration=86400000