spring.application.name=msvc-users
server.port=8001

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/finflow_users
spring.datasource.username=finflow
spring.datasource.password=finflow123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true